### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by oxbits** [prtx/Fast-Fourier-Transform-FFT-in-Notation-Recognition#1]
Traceback (most recent call last):
  File "fft.py", line 50, in <module>
    main()
  File "fft.py", line 39, in main
    amplitude = amplitude[:,0] + amplitude[:,1]
IndexError: too many indices for array

**Comment by oxbits** [comment]
I was trying to use a 32 bit wav at 96000 sample rate.

Your code works with a 16 bit wav at 48000.

**Comment by oxbits** [comment]
Now I'm thinking it's that the problematic file was 1 channel (mono) and the working file is 2 channels (stereo).

**Comment by prtx** [comment]
Thanks for pointing it out @oxbits 
Better late than never right :)
